[toolchain]
# channel = "stable-2024-04-09" # have to remove miri
# channel = "nightly-2024-04-23"
channel = "nightly-2024-10-18"
components = ["rustfmt", "clippy", "rust-src", "miri", "rust-analyzer"]
